linters:
  enable-all: true
  disable:
    - funlen
    - lll
    - varnamelen
    - gomnd
    - cyclop
    - exhaustivestruct
    - gochecknoglobals
    - goerr113
    - wsl
    - gocognit
    - nestif

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
