name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ fromJson(matrix.target).rid }}

    strategy:
      fail-fast: false

      matrix:
        target:
          - '{"goos":"windows","rid":"win-x64","os":"windows-latest"}'
          - '{"goos":"linux","rid":"linux-x64","os":"ubuntu-latest"}'
          - '{"goos":"darwin","rid":"osx-x64","os":"macos-11"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    env:
      GOOS: ${{ fromJson(matrix.target).goos }}
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Install Dependencies (macOS)
        if: ${{ fromJson(matrix.target).goos == 'darwin' }}
        run: brew install graphicsmagick imagemagick
        shell: bash

      - name: Install Build Package
        run: |
          yarn install --frozen-lockfile
        shell: bash

      - name: Build Koi
        run: |
          yarn gulp ciBuild
        shell: bash

      - name: Upload zip for Windows
        if: ${{ fromJson(matrix.target).goos == 'windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: koi-${{ fromJson(matrix.target).rid }}-${{ github.sha }}.zip
          path: build/dist/koishi.zip

      - name: Upload msi for Windows
        if: ${{ fromJson(matrix.target).goos == 'windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: koi-${{ fromJson(matrix.target).rid }}-${{ github.sha }}.msi
          path: build/dist/koishi.msi

      - name: Upload zip for macOS
        if: ${{ fromJson(matrix.target).goos == 'darwin' }}
        uses: actions/upload-artifact@v3
        with:
          name: koi-${{ fromJson(matrix.target).rid }}-${{ github.sha }}.zip
          path: build/dist/koishi.zip

      - name: Upload dmg for macOS
        if: ${{ fromJson(matrix.target).goos == 'darwin' }}
        uses: actions/upload-artifact@v3
        with:
          name: koi-${{ fromJson(matrix.target).rid }}-${{ github.sha }}.dmg
          path: build/dist/koishi.dmg

      - name: Upload pkg for macOS
        if: ${{ fromJson(matrix.target).goos == 'darwin' }}
        uses: actions/upload-artifact@v3
        with:
          name: koi-${{ fromJson(matrix.target).rid }}-${{ github.sha }}.pkg
          path: build/dist/koishi.pkg

      - name: Upload zip for Linux
        if: ${{ fromJson(matrix.target).goos == 'linux' }}
        uses: actions/upload-artifact@v3
        with:
          name: koi-${{ fromJson(matrix.target).rid }}-${{ github.sha }}.zip
          path: build/dist/koishi.zip
