name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ fromJson(matrix.target).rid }}

    strategy:
      fail-fast: false

      matrix:
        target:
          - '{"goos":"windows","rid":"win-x64","os":"windows-latest"}'
          - '{"goos":"linux","rid":"linux-x64","os":"ubuntu-latest"}'
          - '{"goos":"darwin","rid":"osx-x64","os":"macos-latest"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    env:
      GOOS: ${{ fromJson(matrix.target).goos }}
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.19.0'

      - name: Install Build Package
        run: |
          yarn
        shell: bash

      - name: Lint
        run: |
          yarn gulp ciLint
        shell: bash
